### ISSUE TITLE
Fer vista personalitzada per a crear/editar persones

### ISSUE THREAD

**Issue by omartorell** [julian-git/admin-blau#13]
No sé si ho tens previst fer, però per a la taula de persones, potser caldria fer una edició personalitzada. Hi ha molts camps per editar, i s'hauran de separar per seccions i fer-ho una mica més "maco".

**Comment by guillemcabrera** [comment]
He pujat unes imatges a la documentació, carpeta 'views' amb uns esquemes de com podrien ser algunes de les vistes.
Bàsicament és molt similar al que tenim, potser una mica organitzat per categories.

**Comment by julian-git** [comment]
ok, está organitzat bastant tal i com diu en Guillem; no exactament, però amb el temps que hi ha no puc fer més. Pero considero que ja queda bé així.
