### ISSUE TITLE
Llistats en general

### ISSUE THREAD

**Issue by omartorell** [julian-git/admin-blau#17]
Ocultar la columna ID (no sé si a tots els llistats), a l'usuari no li interessa.

**Comment by guillemcabrera** [comment]
si, els ids han de ser coses internes de l'aplicació, l'usuari no n'ha de
fer res!

On Sun, Mar 2, 2014 at 2:50 PM, omartorell notifications@github.com wrote:

> Ocultar la columna ID (no sé si a tots els llistats), a l'usuari no li
> interessa.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/julian-git/admin-blau/issues/17
> .

## 

Guillem Cabrera

**Comment by julian-git** [comment]
ok, ha desaparegut.
