### ISSUE TITLE
Editar/Crear en general

### ISSUE THREAD

**Issue by omartorell** [julian-git/admin-blau#18]
Apareixen botons per crear noves entitats relacionades amb la entitat que estem editant. Segurament hi ha botons que no volem que apareguin (per exemple, crear un nou tipus de quota des de la pantalla de quotes).
A més, si utilitzes el botó, marxes de la pantalla inicial, per tant, perds les dades. O s'arregla o es treuen aquests botons, tal com està pot provocar més d'una emprenyada.

**Comment by julian-git** [comment]
ok, han mort.
