### ISSUE TITLE
Millorar .css

### ISSUE THREAD

**Issue by julian-git** [julian-git/admin-blau#2]
De moment, fem servir el `public/bootstrap/dist/css/bootstrap.min.css`. Entre altres coses, la classe `error` és bastant millorable.

**Comment by guillemcabrera** [comment]
Julian, potser això ens pot interessar per no fer feina de més_ http://www.genbetadev.com/desarrollo-web/temas-de-ui-para-sitios-bootstrap-algunos-gratis-algunos-de-pago

Jo he donat una ullada molt ràpida i aquest té bona pinta: http://startbootstrap.com/sb-admin-v2

**Comment by julian-git** [comment]
Sí, sembla molt xulo. Ho he incorporat, a veure què us sembla. (Atents a les missatges i estadístiques :)

**Comment by julian-git** [comment]
ok, hauriem de fer uns quants tweaks a nivell de facilitat d'usar; per exemple, 
- els menus laterals es podrien resaltar quan són actius;
- les files de les taules podrien acolorir-se millor, sobretot quan el ratolí passa per damunt
