### ISSUE TITLE
ajustar estructura de les taules a les necessitats de la colla

### ISSUE THREAD

**Issue by julian-git** [julian-git/admin-blau#7]
Completar els requeriments i pensar l'estructura de les taules

**Comment by omartorell** [comment]
De moment he modificat les taules necessàries per a la versió 1.0 (rols, categories, persones, families, familie_persone, tipus_quotes, quotes, beneficiaris).
Tanco la issue i si fa falta la tornem a obrir més endavant amb les taules que faci falta.

**Comment by guillemcabrera** [comment]
Alguns comentaris sobre la nova estructura. No sé si sóc massa prim-mirat, però millor que això que és el "core" quedi ben clar abans de seguir:

-pq les taules "tipus_quota" i "categories" necessiten els camps "created_at" i "updated_at"? diria que són innecessaris.

-a les quotes, falta definir d'alguna manera qui n'és el responsable (que és de qui agafem el DNI i el IBAN). hi ha 2 opcions: o un booleà a la taula de relació "beneficiaris" (tipus com fem amb les famílies, tindria el problema de que podrien haver-hi 2 responsables per una quota) o un FK amb el id de la persona a la taula "quotes".

-afegir el camp "comentari" a "families" i "quotes".

-una pijada: es poden canviar els noms "familie" i "persone" a les respectives taules de relació i als camps de FK per familiA i personA?

**Comment by omartorell** [comment]
Responc a l'anterior comentari del Guillem:
- Pq les taules "tipus_quota" i "categories" necessiten els camps "created_at" i "updated_at"? Per si en algun moment volem traçar alguna modificació en aquestes taules (com en la resta de taules de l'aplicació). Són camps que tracta automàticament el Laravel. No ens afecten per res en el codi i ens poden donar alguna pista en algún moment. Encara que són taules que no haurien de patir modificacions... mai se sap. De totes formes, si vols, ho traiem.
- A les quotes, falta definir d'alguna manera qui n'és el responsable. Ja està fet... hi ha una FK a la taula `Quotes`.
- Afegir el camp "comentari" a "families" i "quotes". Ok, ara ho faig i ho pujo.
- Una pijada: es poden canviar els noms "familie" i "persone" a les respectives taules de relació i als camps de FK per familiA i personA? Doncs no és una pijada... jo també vaig pensar el mateix (collons el Julian, que malament que porta el català ;)). Però resulta que hi ha un invent automatitzat per agafar els noms dels camps i taules a partir dels noms de les entitats (és el que té agafar un framework fet per anglosaxons). Si no és un problema greu, va millor deixar-ho així.

**Comment by guillemcabrera** [comment]
Si el Laravel ho fa així cap problema en deixar els camps de 'created_at' i  'updated_at', el dubte és perquè en algunes taules si i en altres no.
Per exemple, no entenc perquè 'beneficiaris', 'castell_persone', 'acuacion_persone', 'esdeveniment_persone' o 'rols' no tenen aquests camps. Això és el que em feia dubtar.

Sobre el responsable de les quotes, crec que mirava una versió antiga de l'esquema. Recordeu que NOMÉS hi ha 1 responsable de quota, podeu posar-ho en singular si voleu per evitar malentesos.

OK a deixar 'familie' i 'quote' si facilita el desenvolupament. Recordem deixar-ho molt clar a la documentació.

**Comment by omartorell** [comment]
- De les taules que no tenen timestamps: `Beneficiaris` m'ho vaig deixar el cap de setmana, però a la última versió ja està arreglat, `castell_persona` i `actuacion_persone` no estan revisades i `rol` és una taula NO mantenible des de l'aplicació i per tant el tracking no té raó de ser.
- La FK de quotes amb persona (o sigui, el responsable) té el nom que té per convencions del Laravel (el mateix que passa amb les 'e' finals). Es pot canviar el nom, però aleshores lies el codi. Està clar que el responsble només serà 1 persona, la FK no dóna lloc a més.
