### ISSUE TITLE
Fem una taula Users?

### ISSUE THREAD

**Issue by julian-git** [julian-git/admin-blau#8]
La qüestió és si un casteller pot tenir diverses logins. Jo crec que si, per que d'aquesta manera nosaltres, per exemple, podem fer tant tasques de casteller a peu sense tenir por de trepitjar el codi.
Més a més, no es sobrecarrega tant la taula casteller.
Per tant, proposo una taula User que te, apart de `username`, `password` etc,  un clau forany `castellers_fk` que diu a qui va associat aquest usuari.

**Comment by omartorell** [comment]
No entenc el motiu de tenir dos logins... per mi, un casteller (o persona) és un usuari. Si ho fem en taules separades només fa que complicar el codi i les relacions.
I més, si tenim en compte que els castellers podran entrar a l'aplicació per donar-se d'alta d'activitats... que hauriem de fer per donar d'alta un casteller? Donar d'alta dos registres? No té massa sentit. Jo voto per una sola taula.

**Comment by julian-git** [comment]
ok, jo ho pensava pel tema de les rols i l'accès a segons quines taules. Nosaltres per exemple podriem entrar com a admins (podent tocar tot) o com a castellers que només poden donar-se d'alta a activitats. Desprès hi hauria les rols que puguin donar d'alta i modificar activitats, i potser encara d'altres perfils que poden tocar els diners de les quotes etc.

L'altra opció seria tenir una taula `Rols` que diu quins rols pot tenir cada casteller, i deixar usuari i login a la taula `Casteller`.
